#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KEY_DIR="${KEY_DIR:-${ROOT_DIR}/../Loger_key}"
UPLOADER_DIR="${UPLOADER_DIR:-${KEY_DIR}/LogUploader/LogUploader}"
ASSET_DIR="${ASSET_DIR:-${ROOT_DIR}/app/src/main/assets/log_upload}"
PRIVATE_KEY_PATH="${PRIVATE_KEY_PATH:-${KEY_DIR}/private_key.pem}"
PUBLIC_KEY_PATH="${PUBLIC_KEY_PATH:-${KEY_DIR}/rsa_pub_pkcs1.pem}"
UPLOADER_PRIVATE_KEY_PATH="${UPLOADER_PRIVATE_KEY_PATH:-${UPLOADER_DIR}/private_key.pem}"
UPLOADER_PUBLIC_KEY_PATH="${UPLOADER_PUBLIC_KEY_PATH:-${UPLOADER_DIR}/rsa_pub_pkcs1.pem}"
LOG_DECRYPTER_DIR="${LOG_DECRYPTER_DIR:-${ROOT_DIR}/../log-decrypter}"
LOG_DECRYPTER_PRIVATE_KEY_PATH="${LOG_DECRYPTER_PRIVATE_KEY_PATH:-${LOG_DECRYPTER_DIR}/public/private_key.pem}"
PACKAGE_MANAGER="${PACKAGE_MANAGER:-npm}"
ROTATE_KEY=false

usage() {
    cat <<'EOF'
Usage:
  scripts/update_log_upload_assets.sh [--rotate-key] [--package-manager <npm|bun|pnpm|yarn>]

Options:
  --rotate-key                  Generate a new private_key.pem before building.
  --package-manager <manager>   Build LogUploader with npm, bun, pnpm, or yarn.
  -h, --help                    Show this help message.

Environment overrides:
  KEY_DIR             Defaults to ../Loger_key.
  UPLOADER_DIR        Defaults to $KEY_DIR/LogUploader/LogUploader.
  ASSET_DIR           Defaults to app/src/main/assets/log_upload.
  PRIVATE_KEY_PATH    Defaults to $KEY_DIR/private_key.pem.
  PUBLIC_KEY_PATH     Defaults to $KEY_DIR/rsa_pub_pkcs1.pem.
  UPLOADER_PRIVATE_KEY_PATH
                      Defaults to $UPLOADER_DIR/private_key.pem.
  UPLOADER_PUBLIC_KEY_PATH
                      Defaults to $UPLOADER_DIR/rsa_pub_pkcs1.pem.
  LOG_DECRYPTER_DIR   Defaults to ../log-decrypter.
  LOG_DECRYPTER_PRIVATE_KEY_PATH
                      Defaults to $LOG_DECRYPTER_DIR/public/private_key.pem.
  PACKAGE_MANAGER     Defaults to npm.
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --rotate-key)
            ROTATE_KEY=true
            shift
            ;;
        --package-manager)
            if [[ $# -lt 2 ]]; then
                echo "--package-manager requires an argument" >&2
                exit 1
            fi
            PACKAGE_MANAGER="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
done

require_command() {
    local command_name="$1"
    if ! command -v "${command_name}" >/dev/null 2>&1; then
        echo "Required command not found: ${command_name}" >&2
        exit 1
    fi
}

require_file() {
    local path="$1"
    if [[ ! -f "${path}" ]]; then
        echo "Required file not found: ${path}" >&2
        exit 1
    fi
}

require_dir() {
    local path="$1"
    if [[ ! -d "${path}" ]]; then
        echo "Required directory not found: ${path}" >&2
        exit 1
    fi
}

run_build() {
    case "${PACKAGE_MANAGER}" in
        npm)
            npm run build
            ;;
        bun)
            bun run build
            ;;
        pnpm)
            pnpm run build
            ;;
        yarn)
            yarn build
            ;;
        *)
            echo "Unsupported package manager: ${PACKAGE_MANAGER}" >&2
            exit 1
            ;;
    esac
}

copy_key_file() {
    local source_path="$1"
    local target_path="$2"
    local mode="$3"

    mkdir -p "$(dirname "${target_path}")"
    if [[ "${source_path}" != "${target_path}" ]]; then
        cp "${source_path}" "${target_path}"
    fi
    chmod "${mode}" "${target_path}"
}

sync_keys_to_uploader() {
    copy_key_file "${PRIVATE_KEY_PATH}" "${UPLOADER_PRIVATE_KEY_PATH}" 600
    copy_key_file "${PUBLIC_KEY_PATH}" "${UPLOADER_PUBLIC_KEY_PATH}" 644
}

sync_key_to_log_decrypter() {
    require_dir "${LOG_DECRYPTER_DIR}"
    copy_key_file "${PRIVATE_KEY_PATH}" "${LOG_DECRYPTER_PRIVATE_KEY_PATH}" 600
}

write_public_key_js() {
    local public_key_js="${UPLOADER_DIR}/src/config/publicKey.js"
    local temp_public_key_js
    temp_public_key_js="$(mktemp "${public_key_js}.XXXXXX")"

    {
        printf '%s\n' '// RSA public key generated by scripts/update_log_upload_assets.sh.'
        printf '%s' 'export const PUBLIC_KEY_PEM = `'
        cat "${PUBLIC_KEY_PATH}"
        printf '%s\n' '`;'
    } > "${temp_public_key_js}"

    mv "${temp_public_key_js}" "${public_key_js}"
}

sync_dist_to_assets() {
    local dist_dir="${UPLOADER_DIR}/dist"
    require_dir "${dist_dir}"
    require_file "${dist_dir}/index.html"

    mkdir -p "${ASSET_DIR}"
    if command -v rsync >/dev/null 2>&1; then
        rsync -a --delete "${dist_dir}/" "${ASSET_DIR}/"
    else
        find "${ASSET_DIR}" -mindepth 1 -maxdepth 1 -exec rm -rf {} +
        cp -R "${dist_dir}/." "${ASSET_DIR}/"
    fi

    sed -i -E 's#(src|href)="/#\1="./#g' "${ASSET_DIR}/index.html"
}

verify_assets() {
    local index_html="${ASSET_DIR}/index.html"
    local public_key_probe
    local main_js
    require_file "${index_html}"

    main_js="$(find "${ASSET_DIR}/assets" -maxdepth 1 -type f -name 'index-*.js' -print -quit)"
    if [[ -z "${main_js}" ]]; then
        echo "No built index-*.js found in ${ASSET_DIR}/assets" >&2
        exit 1
    fi

    public_key_probe="$(awk 'NR == 2 { print; exit }' "${PUBLIC_KEY_PATH}")"
    if [[ -z "${public_key_probe}" ]] || ! grep -Fq "${public_key_probe}" "${main_js}"; then
        echo "Built JS does not contain the generated public key" >&2
        exit 1
    fi

    while IFS= read -r asset_ref; do
        asset_ref="${asset_ref#./}"
        require_file "${ASSET_DIR}/${asset_ref}"
    done < <(grep -oE '(src|href)="\./[^"]+"' "${index_html}" | sed -E 's/^(src|href)="\.\/([^"]+)"$/\2/')
}

require_command openssl
require_command "${PACKAGE_MANAGER}"
require_dir "${KEY_DIR}"
require_dir "${UPLOADER_DIR}"
require_file "${UPLOADER_DIR}/package.json"

if [[ "${ROTATE_KEY}" == "true" || ! -f "${PRIVATE_KEY_PATH}" ]]; then
    openssl genrsa 2048 | openssl pkcs8 -topk8 -nocrypt -out "${PRIVATE_KEY_PATH}"
fi

require_file "${PRIVATE_KEY_PATH}"
openssl rsa -in "${PRIVATE_KEY_PATH}" -pubout -out "${PUBLIC_KEY_PATH}"
sync_keys_to_uploader
sync_key_to_log_decrypter
write_public_key_js

(
    cd "${UPLOADER_DIR}"
    run_build
)

sync_dist_to_assets
verify_assets

cat <<EOF
Log upload assets updated.
Private key: ${PRIVATE_KEY_PATH}
Public key: ${PUBLIC_KEY_PATH}
Uploader private key: ${UPLOADER_PRIVATE_KEY_PATH}
Uploader public key: ${UPLOADER_PUBLIC_KEY_PATH}
Log decrypter private key: ${LOG_DECRYPTER_PRIVATE_KEY_PATH}
Uploader: ${UPLOADER_DIR}
Android assets: ${ASSET_DIR}
EOF
